### PR TITLE
Contrastive Neural Ratio Estimation

### PR DESCRIPTION
**Pull request by bkmi**
- [x] code conventions
- [x] testing
- [x] documentation

### CODE REVIEW

**Comment by bkmi** [comment]
My commits do not follow the guidelines, but I believe it is possible to squash them when this is pulled into the main branch.

**Comment by francois-rozet** [comment]
Hello @bkmi, thank you for your contribution 🔥 I am a bit busy currently, so I'll review the PR as soon as possible. Cheers!

**Comment by glouppe** [comment]
Any news on this? Hopefully, 2304.10978 will be accepted in a few days. It would be nice to have CNRE in lampe.

**Comment by francois-rozet** [comment]
I'll merge this tomorrow!

**Comment by francois-rozet** [comment]
As you warned me, the provided docstrings do not render correctly, but I can fix that. However, while it is great that the explanation closely follows the content of the manuscript, I think the introduction of new notations that differ greatly from other NRE methods should be avoided.

So I re-read the paper a few times, and tried to condense and reformulate the method while introducing as few new concepts as possible. Tell me what you think!

| Before | After |
|--------|-------|
| Screenshot from 2023-06-13 23-04-55 | Screenshot from 2023-06-13 23-06-07 |

**Comment by glouppe** [comment]
Is it really a good idea to remove hyper-parameters ($\gamma$) defined in the original paper?

**Comment by francois-rozet** [comment]
With $\gamma$ added back.

**Comment by francois-rozet** [comment]
By the way, in my experiments, using `CNRELoss` instead of `NRELoss`, even with $K = 2$, makes the resulting estimator super smooth and very well calibrated, at least on a few toy problems.

image

**Comment by bkmi** [comment]
I wanted to run calibration checks but never got around to it, thanks for doing that! Exciting that it works in that way!

I also plan to redo some experiments with version this version which fixed a bug in the definition of `\gamma`... 

It's a nice way to have it rewritten, although it may be confusing that the notation is different than in the paper. Your version is certainly more concise!

**Comment by francois-rozet** [comment]
> although it may be confusing that the notation is different than in the paper.

Maybe we can add a note to say that $d(\Theta, x)$ is actually $q(y \in \{1, \dots, K} | \Theta, x) = 1 - q(y = 0 | \Theta, x)$ in the paper?

> I think the conflict is easily dealt with, right?

Yes, this should be easy, I'll edit the PR with my changes and fix the conflicts.

**Comment by francois-rozet** [comment]
Ah these errors come from an incompatibility with Zuko's latest version.

**Pull request merged**
